name: Feature Branch CI

on:
  push:
    branches:
      - test

jobs:
  test:
    if: github.ref != 'refs/heads/main' # Run only if not the main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:cypress
