name: Feature Branch CI

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --force

      - name: Install Cypress
        run: npm install cypress --force

      - name: Run Cypress tests
        run: | 
            $(npm bin)/cypress run --spec "cypress/e2e/test_Folder/*.js"
